################################################
#               Survival Games                 #
#                                              #
#               Originally by                  #
#              Double0negative                 #
#                                              #
#          Updated and Maintained by           #
#            Keiaxx and Rushnett               #
#                                              #
################################################ 
# WARNING: Everything in this file is TAB and  #
# SPACE sensitive. If you accidentally space   #
# something incorrectly, or use the TAB button #
# on your keyboard to edit this file, things   #
# will break. Please consult this website to   #
# check your config file before asking us for  #
# help!                                        #
#       Yaml Parser: http://k31.us/yaml        #
################################################

#Do NOT touch this!
config-version: 3

#Enable debug messages
debug: false

#Should the plugin handle the chat (Apply rank prefixes automatically)
#If you do not want the plugin to handle chat, and use your own
#chat formatting plugin, use the {SURVIVALGAMES} tag to implement
#rank prefixes (Ex. EssentialsChat)
handlechat: false

#Set how many players are needed for the game
#to auto-start. Once the player limit is reached
#it will wait for x amount of seconds for
#additional players. Auto start vote means that
#x percent of players need to vote with /sg vote
#for the game to begin
auto-start-players: 20
auto-start-time: 20
auto-start-vote: 75

#If the player queue is enabled then if a player
#tries to join a game that is not joinable
#(ie ingame) the player will be added to a
#queue line to join the next time the game
#is open
enable-player-queue: true

#If set to true, commands not associated with
#the Survival Games will not be allowed to be run 
#by players in-game.
disallow-commands: true
#If disallow-commands is set to true, you can use
#the cmdwhitelist section below to whitelist certain
#commands.
cmdwhitelist: 
- 'kit' 

#Set how long the grace period for be after the start of 
#the game in seconds.
grace-period: 20

#Controlls if chests should be restocked on the first
#night. If set to true this will also have the side
#effect of setting the world time to day at the start
#of the game. This is only temporary until per-arena time
#has been implemented.
restock-chest: true

#Here you can control block placing and breaking. 
block:
  place:
    whitelist:
    - 18
    - 105
    - 31
    - 37
    - 38
    - 50
    - 103
    - 43
  break:
    whitelist:
    - 18
    - 105
    - 31
    - 37
    - 38
    - 50
    - 103
    - 43

#How many blocks to rollback per-tick
#The higher this settings the fast each
#arena will be reset but will cause more
#lag
rollback:
  per-tick: 100
 

#Settings for when the game nears end. This runs
#when there are only x amount of players
#remaining. If place chest is enabled then
#when the player limit is reached, a chest
#will be placed inside the radius of every 
#remain player containing random items for 
#that player. If fire-lighting is enabled
#then a lighting strike will be fired at the
#location of each player every x seconds to
#notify the other players of their location
#If playerGlow is enabled, players will have
#a randomly colored glow around them to allow
#players to easily find one another.
endgame:
  players: 3
  playerGlow: true
  fire-lighting:
    enabled: true
    interval: 20
  
  
# If disabled, games can essentially last forever if two people decide to
# not do anything lol.
# This mode teleports players to the center of the map, defined by the first
# spawn point. Once teleported, the deathmatch starts, and a world border of
# a specified radius takes effect to disallow users from running away.
# If playerGlow is enabled, players will have
# a randomly colored glow around them to allow
# players to easily find one another.

deathmatch:
  enabled: false
  # Time until deathmatch, in minutes
  time: 30
  playerGlow: true
  border:
     enabled: true
     # Radius in Blocks
     radius: 30
  
#Settings for connecting to and 
#SQL server. These settings will
#be used for  the online webstats
#Prefix is what all tables used for 
#SurvivalGames will be
#prefixed with. This should stay the same
#for most cases.
sql:
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: ''
  database: 'survivalgames'
  prefix: 'sg_'
 
 
# stats: Enable or disable points tracking. If enabled,
#        sql settings above MUST be set up or else plugin
#        will be disabled upon startup
stats:
  enabled: true
# player: The number of points a player will recieve upon each kill or death.
  player:
    kill: 2
    death: -1
# This section allows you to create values for MAX points given for a win. 
# MAX point are only give when 30 minutes are reached, 
# and anything less is determined by MAXPOINTS * (gameTime/TotalTime).
# equation: CEILING(addFactor+(multiFactor*(numberOfPlayers*ratio)))
  win:
    multiFactor: 4
    addFactor: 4
    ratio: 0.27
    
###########################################################
################### Endgame Compass #######################
###########################################################  
compass:
  enabled: true
  radius: 200


    
    
    


