name: SurvivalGames
version: 0.6.0-beta
main: org.mcsg.survivalgames.SurvivalGames
authors: [Double0negative, Pocketkid2, Keiaxx, Rushnett]
description: Fully Automated Hunger Games Plugin!
commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]