name: SurvivalGames
version: 0.5.9
main: org.mcsg.survivalgames.SurvivalGames
authors: [Double0negative, Pocketkid2]
description: Fully Automated Hunger Games Plugin!
commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]